MAIN_SESSION_ID = "main-session"
DEFAULT_THREAD_ID = "main-agent"
WORKFLOW_THREAD_ID_PREFIX = "task-"

MAX_LOG_LENGTH = 200
MAX_NODE_OUTPUT_LENGTH = 300
MAX_SCRIPT_OUTPUT_LENGTH = 500

TEMPLATE_QUOTA = 2
SUCCESS_QUOTA = 3
MAX_WORKFLOW_RETRIES = 5

SCHEDULER_TIMEOUT = 5
